language: d
sudo: false
dist: focal

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.093.1
  allow_failures:
    - d: dmd-nightly

addons:
  apt:
    packages:
      - ninja-build

install:
  - gem install bundler
  - bundle install
  - dub fetch unit-threaded --version=0.7.21
  - dub fetch unit-threaded --version=0.7.11
  - dub fetch unit-threaded --version=0.7.8
  - dub fetch cerealed --version=0.6.8

script:
  - ./bootstrap.sh make
  - ./run-tests.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
