name: CI
on: [push, pull_request]

jobs:
    test:
        name: Dub Test
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-2.094.2]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: seanmiddleditch/gha-setup-ninja@master
            - run: mkdir build && cd build && cmake -G Ninja .. && cmake --build build
            - uses: actions/checkout@v2
            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: dub -q test
